### ISSUE TITLE
User Upgrade Question

### ISSUE THREAD

**Issue by kreativedev** [Contex/XenAPI#31]
Love what you did with the ability to upgrade a user. What I'm wondering is if there is a way to use the API to extend a users current subscription. Like be able to use the upgradeuser, and pass in a new end date, or a way to extend the subscription by X amount of months. Is this something that could be possible or somewhat out there and not very possible to add?

**Comment by Contex** [comment]
There should be a parameter called "end_date" for the upgradeuser action if I recall correctly. This parameter accepts a unix timestamp as the argument and it should update the end date of the user's upgrade with what you've specified. 

I also recall adding a "result" key in the JSON object response of upgradeuser that specifies if the upgrade was new or already existed (meaning the upgrade was edited instead of created). 

That's just from the top of my head but please try it out and I'll add something for it if the functionality doesn't exist.

**Comment by Contex** [comment]
I could add the extend x months parameter as that would be easier considering the Unix timestamp has to be the same as the server's timestamp. 

I'll try to get that done this week.

**Comment by Contex** [comment]
Leaving it as is, use unix timestamp
